# Generated by Django 3.2.16 on 2023-02-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20230228_1621'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='could_not_follow_itself',
        ),
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_following',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'following'), name='unique_user_following'),
        ),
    ]
